version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm prune
  - npm update

build_script:
  - node --version
  - npm --version
  - npm run dist

test: off

deploy:
    # FTP deployment provider settings
  - provider: FTP
    protocol: sftp
    host: play04.play-entry.com
    username: entry
    password:
      secure: AAMMJ21gGJ9i2Bhd7eCzeg==
    folder: 
    artifact: /.*\.exe/