version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

environment:
  GH_TOKEN:
    secure: +sYL7dvMYAqkqjswuvxZW4vS4Tpy5pc5p6vsdrLWt757ljOMwm2tVNLifIV2qHgx

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm prune
  - npm update

build_script:
  - node --version
  - npm --version
  - npm run dist

test: off

artifacts:
  - path: '**\*.exe'
    name: setup

  - path: '**\*.nupkg'
    name: package

deploy:
  - provider: FTP
    protocol: sftp
    host: play04.play-entry.com
    username: entry
    password:
      secure: AAMMJ21gGJ9i2Bhd7eCzeg==
    folder: 
    artifact: 